### ISSUE TITLE
WitheList with FiveM

### ISSUE THREAD

**Issue by LexBoosT** [Equicord/Equicord#29]
### Content

Hello, I have a problem with Equicord., in fact the whitlist is made by discord.
And when I try to co, I say no discord identifier.
"I test without plugin also"
### Request Agreement

- [X] I have read the requirements for opening an issue above

**Comment by KrystalSkullOfficial** [comment]
1st. Please Use English, and good English
2nd. Your discord is 30(ish) seconds old _(I say this because the moment you joined our server discord themselves flagged it as a scam account)_, so it is either an issues with your account, or you're enabling plugins without reading what they actually do. 
Try disabling these plugins and seeing if this issue goes away _(if not blame FiveM because its bad)_
![Capture](https://github.com/user-attachments/assets/3f060f3d-d5ce-4219-88ec-a19305672631)
![Capture](https://github.com/user-attachments/assets/51758541-065e-45b9-960e-95d39036960c)
